repository:
  description: A Hacker News reader focused on content and readability.
  homepage: https://hn.hsblhsn.me
  topics: hackernews, redesign, reader
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system.
  - name: feature
    color: 336699
    description: New functionality.
  - name: documentation
    color: AAAA00
    description: New functionality.

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams:
            - core
      required_status_checks:
        strict: true
        contexts:
          - build
      enforce_admins: false
      required_linear_history: false
      restrictions:
        apps: []
        users: []
        teams: []