name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install dependencies
        run: go mod download
      - name: Mock embedded assets
        run: mkdir -p ./frontend/build && touch ./frontend/build/index.html
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
