name: "Preview Link"

on:
  pull_request:
    branches:
      - main

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const link = `https://gh${context.sha.substr(0,7)}---hackernews-reader-jw5iyahjwq-uc.a.run.app`;
            const msg = `If everything goes right, a preview of this PR will be available shortly!\n\n` +
              `Check [${link}](${link})\n\n`+
              `Thank you! :heart:`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg,
            });
